# Site settings
title: 카카오뱅크 채널파트 워크샵준비위원회
motto: 될대로 되라지
email: jayden.yoo@kakaobank.com
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://kabangchnl_wpc2.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username: HighLvRiver

# Build settings
markdown: kramdown
