# Site settings
title: 채널|워크샵준비위원회
motto: 어떻게든 놀다 오겠지요...?
email: jayden.yoo@kakaobank.com
description: # this means to ignore newlines until "baseurl:"
  
baseurl: "/Kabang.Channel.WPC/" # the subpath of your site, e.g. /blog/
url: "https://highlvriver.github.io/Kabang.Channel.WPC/" # the base hostname & protocol for your site
twitter_username: 
github_username: HighLvRiver

# Build settings
markdown: kramdown
